### ISSUE TITLE
Laravel 11 support?

### ISSUE THREAD

**Issue by carestad** [jenssegers/model#49]
Hi!

Thanks for a great library! Is there any chance it will support Laravel 11 in the near future? :crossed_fingers:

**Comment by joshcadman01** [comment]
Hi @carestad

I have just created a PR for this to add Laravel 11 support. In the meantime you can use [my forked version](https://packagist.org/packages/joshcadman01/jenssegers-model) by running `composer require joshcadman01/jenssegers-model`

**Comment by jenssegers** [comment]
Done!
