### ISSUE TITLE
1 abstract method and must therefore be declared abstract or implement the remaining methods (ArrayAccess::offsetGet)

### ISSUE THREAD

**Issue by BonnieSawe** [jenssegers/model#52]
@jenssegers Model::offsetGet is commented out 

We are getting this error class contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ArrayAccess::offsetGet)

**Comment by jenssegers** [comment]
Fixed 👍

**Comment by mikebronner** [comment]
@BonnieSawe hey Boniface! Good to see you.

**Comment by BonnieSawe** [comment]
Hey @mikebronner, it's good to see you too! 😊
