### ISSUE TITLE
How to take advantage of eloquent relationships?

### ISSUE THREAD

**Issue by raghavendra89** [jenssegers/model#8]
Hi,

This looks great for my new project.

Can you please give more documentation on how to use eloquent relationships?

More details: I'm building a Client Portal for SuiteCRM. I'm using the REST api to fetch the data. In the crm contacts have one to many relationships with the cases model. I would like to reflect this relationship in the Laravel, so I can do something like this:

$cases = Contact::find(id)->cases;

Can you please you give example of how to use relationships with your model?

Thanks,

**Comment by jenssegers** [comment]
Relations are not within the scope of this package. If you want Eloquent relations, why not just use Eloquent? :)

**Comment by vwasteels** [comment]
Hello @jenssegers 
Can you explain more about this example you gave with REST relations ?
I tried it but it seems that this method is expecting something else in return than directly the Eloquent objects : 

```Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation```

am I seeing it the wrong way ?

Thank you
